plugins {
    id "net.fabricmc.fabric-loom" version "${loom_version}" apply false
    id "net.neoforged.moddev" version "${moddev_version}" apply false
    id 'org.moddedmc.wiki.toolkit' version '0.5.0'
}

subprojects {
    apply plugin: 'java-library'

    group = "com.github.hugman"
    version = rootProject.version

    base {
        archivesName = "${mod_id}-${project.name}"
    }

    repositories {
        mavenCentral()
        maven { url 'https://maven.fabricmc.net/' } // Mixin, for the common project
        maven { url 'https://maven.terraformersmc.com' } // Required for Biolith and Mod Menu
    }

    dependencies {
        compileOnly "com.google.code.findbugs:jsr305:3.0.2"
    }

    tasks.withType(JavaCompile).configureEach {
        it.options.encoding = "UTF-8"
        it.options.release = 25
    }

    java {
        withSourcesJar()

        sourceCompatibility = JavaVersion.VERSION_25
        targetCompatibility = JavaVersion.VERSION_25
    }

    tasks.withType(Jar).configureEach {
        from(rootProject.file("LICENSE.md")) {
            rename { "${it}_${mod_id}" }
        }
    }

    // for JitPack
    configurations.configureEach {
        resolutionStrategy.cacheChangingModulesFor 0, 'seconds'
    }
}

wiki {
    docs {
        promenade {
            root = file('docs')
        }
    }
}
