project_id: "427504"
api_token_env: "CROWDIN_PERSONAL_TOKEN"
preserve_hierarchy: true

files:
  - source: "src/client/resources/assets/promenade/lang/en_us.json"
    translation: "src/client/resources/assets/promenade/lang/%locale_with_underscore%.json"
    dest: "promenade.json"