blank_issues_enabled: false
contact_links:
  - name: Official Website
    url: https://dawnteammc.github.io/promenade
    about: Visit the official website for the mod for more information.
  - name: Discord Server
    url: https://discord.gg/8ksTVJu
    about: Join us for further real-time support and other questions about the mod.