name: Release Major
on: [ workflow_dispatch ] # Manual trigger
jobs:
  build:
    strategy:
      matrix:
        java: [ 11 ]
        os: [ ubuntu-20.04 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get previous tag
        id: previous-tag
        uses: WyriHaximus/github-action-get-previous-tag@1.0.0
      - name: Get SemVer increments
        id: semver
        uses: WyriHaximus/github-action-next-semvers@v1.0
        with:
          version: ${{ steps.previous-tag.outputs.tag }}
      - name: Create version tag
        uses: actions/github-script@v3
        with:
          github-token: ${{ github.token }}
          script: |
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/v${{ steps.semver.outputs.major }}",
              sha: context.sha
            })
      - name: Fetch tags
        run: git fetch --tags
      - name: Get current tag
        id: current-tag
        uses: WyriHaximus/github-action-get-previous-tag@1.0.0
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Make Gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      - name: Build and release
        run: ./gradlew generateChangelog build curseforge github modrinth --stacktrace -PlastTag="${{ steps.previous-tag.outputs.tag }}" -PcurrentTag="${{ steps.current-tag.outputs.tag }}"
        env:
          CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_API_KEY }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Capture build artifacts
        if: ${{ runner.os == 'Linux' && matrix.java == '11' }}
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: build/libs/