name: Upload translations to Crowdin

on:
  pull_request: # this is only for testing
  push:
    paths:
      - 'src/main/resources/assets/promenade/lang/en_us.json'
    branches: [ dev ]

jobs:
  crowdin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Crowdin push
        uses: crowdin/github-action@v1
        with:
          upload_config: 'crowdin.yml'
          upload_sources: true
          upload_translations: false
          download_translations: false
        env:
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}